# Number 1

In [1]:
import numpy as np

In [2]:
matrix_A=np.array([[2,2,3],[-2,7,4],[-3,-3,-4],[-8,2,3]])
print(matrix_A)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]
 [-8  2  3]]


# i)

In [3]:
new_column=([[1],[5],[4],[8]])
new_matrix=np.hstack((matrix_A,new_column))
print(new_matrix)

[[ 2  2  3  1]
 [-2  7  4  5]
 [-3 -3 -4  4]
 [-8  2  3  8]]


In [4]:
determinantA=np.linalg.det(new_matrix)
print(determinantA)

-667.0000000000003


# ii)

In [5]:
reduced_matrix=np.delete(matrix_A,3,axis=0)
print(reduced_matrix)

[[ 2  2  3]
 [-2  7  4]
 [-3 -3 -4]]


In [6]:
determinantA=np.linalg.det(reduced_matrix)
print(determinantA)

9.000000000000005


# iii)

In [8]:
AT=np.transpose(matrix_A)
print(AT)

[[ 2 -2 -3 -8]
 [ 2  7 -3  2]
 [ 3  4 -4  3]]


In [9]:
AAT=np.dot(matrix_A,AT)
print(AAT)

[[ 17  22 -24  -3]
 [ 22  69 -31  42]
 [-24 -31  34   6]
 [ -3  42   6  77]]


In [13]:
determinantA=np.linalg.det(AAT)
print(determinantA)

-5.1884970888279274e-11


In [ ]:
#Therefore AAT is invertable

# iv)

In [14]:
ATA=np.dot(AT,matrix_A)
print(ATA)

[[ 81 -17 -14]
 [-17  66  52]
 [-14  52  50]]


In [15]:
determinantA=np.linalg.det(ATA)
print(determinantA)

45642.00000000001


In [ ]:
#The ATA matrix is invertable

## Number 2

# i)

In [20]:
x=np.array([[25,2],[5,26],[3,7]])
x.shape

(3, 2)

# ii)

In [18]:
XT=np.transpose(x)
print(XT)

[[25  5  3]
 [ 2 26  7]]


# iii)

In [13]:
x = np.array([[25,2],[5,26],[3,7]])
print(x)
x_scalar = np.dot(3,x)
print(x_scalar)

[[25  2]
 [ 5 26]
 [ 3  7]]
[[75  6]
 [15 78]
 [ 9 21]]


# iv)

In [23]:
x =np.array([[25,2],[5,26],[3,7]])
A=np.array([[3,4],[5,6],[7,8]])
multiplication=A*x
print(multiplication)

[[ 75   8]
 [ 25 156]
 [ 21  56]]


# v)

## number 3

# i)

In [7]:
import numpy as np

In [27]:
x=np.array([25,2,5])
print(x)

[25  2  5]


# ii)

In [29]:
x=np.array([25,2,5])
x.shape

(3,)

# iii)

In [30]:
XT=np.transpose(x)
print(XT)

[25  2  5]


# iv) 
compute its Norm

In [31]:
magnitude=np.linalg.norm(x)
print(magnitude)

25.573423705088842
